"""время отправки сообщений ставиться автоматически

Revision ID: 2a2d272a22ec
Revises: 3cf79028fad8
Create Date: 2025-06-07 16:32:25.245840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a2d272a22ec'
down_revision: Union[str, None] = '3cf79028fad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
